name: build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  compile-flags: "-c Release"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '10.0'
    - name: Build BedrockLauncher.Core
      run: dotnet build BedrockLauncher.Core/BedrockLauncher.Core.csproj ${{ env.compile-flags }}
    - name: Set Version
      run: |
          $version = "$(Get-Date -Format 'yy.M.d.HHmm')"; $file = 'BedrockLauncher.Core/BedrockLauncher.Core.csproj'; (Get-Content $file) -replace '<Version>.*?</Version>', "<Version>$version</Version>" | Set-Content $file
    - name: Publish BedrockLauncher.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with: 
        PROJECT_FILE_PATH: BedrockLauncher.Core/BedrockLauncher.Core.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
