name: build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  compile-flags: "-c Release"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: Build BedrockLauncher.Core
      run: dotnet build BedrockLauncher.Core/BedrockLauncher.Core.csproj ${{ env.compile-flags }}
    - name: Set Version
      run: |
          for /f "tokens=2 delims==" %d in ('wmic os get localdatetime /value ^| findstr "="') do @set dt=%d
          for /f "tokens=1-2 delims=:" %a in ("%TIME: =0%") do @set h=%a & set m=%b
          set v=%dt:~4,2%.%dt:~6,2%.%dt:~2,2%.%h%%m:~0,2%
          powershell -Command "(Get-Content BedrockLauncher.Core/BedrockLauncher.Core.csproj) -replace '<Version>[^<]*</Version>', '<Version>%v%</Version>' | Set-Content BedrockLauncher.Core/BedrockLauncher.Core.csproj"
    - name: Publish BedrockLauncher.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with: 
        PROJECT_FILE_PATH: BedrockLauncher.Core/BedrockLauncher.Core.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
